apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    app: auth
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30080
  type: NodePort
